name: Deploy to GitHub Pages

on:
  push:
    branches: [ vue_dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm ci  # 使用 ci 而不是 install
        npm install -g @vue/cli-service  # 全局安装 vue-cli-service

    - name: Build
      run: |
        chmod +x node_modules/.bin/vue-cli-service  # 添加执行权限
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: dist
